project:
  name: Template Worker
  version: 1.0.0

spring:
  config:
    import:
      - postgres.yml
      - batch.yml
      - kafka.yml
  application:
    name: batch-core

  main:
    time-zone: Asia/Seoul
  jackson:
    time-zone: Asia/Seoul

  batch:
    job:
      enabled: false

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics,loggers
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
    prometheus:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: ${OTEL_SAMPLING_PROBABILITY:1.0}
  otlp:
    tracing:
      endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4318}/v1/traces
      connect-timeout: 5s
      timeout: 10s
    metrics:
      endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4318}/v1/metrics
      connect-timeout: 5s
      timeout: 10s
    logs:
      endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4318}/v1/logs
      connect-timeout: 5s
      timeout: 10s

logging:
  level:
    root: INFO
    org.springframework.batch: INFO
    com.template.worker: INFO
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

---

spring:
  config:
    activate:
      on-profile: local

logging:
  level:
    org.springframework.batch.core.job: INFO
    org.springframework.batch.core.step: INFO
    org.springframework.batch.core.partition: DEBUG
    org.springframework.batch.core.step.tasklet: DEBUG
    com.template.worker: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{30} - %msg%n"
---

spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    root: INFO
    org.springframework.batch: INFO
    com.template.worker: INFO
    org.springframework.batch.core.job: INFO
    org.springframework.batch.core.step: INFO
    org.springframework.batch.core.partition: DEBUG
    org.springframework.batch.core.step.tasklet: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{30} - %msg%n"
