spring:
  batch:
    jdbc:
      initialize-schema: always

    # 공통 설정
    common:
      retry:
        max-attempts: 3
        backoff-ms: 2000
      skip:
        max-count: 1000

    # Job 별 상세 설정
    jobs:
      # 1. 청구 상세 생성 Job (InvoiceItemJob)
      invoice-item:
        chunk-size: 3000
        page-size: 3000
        partition:
          grid-size: 12
          thread:
            core-pool-size: 12
            max-pool-size: 16
            queue-capacity: 1000

      # 2. 청구서 생성 Job (InvoiceJob)
      invoice:
        chunk-size: 1000
        page-size: 1000
        partition:
          grid-size: 4
          thread:
            core-pool-size: 4
            max-pool-size: 8
            queue-capacity: 1000
