spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5433}/${POSTGRES_DATABASE:app_db}?reWriteBatchedStatements=true
    username: ${POSTGRES_USER:app_user}
    password: ${POSTGRES_PASSWORD:app_password}
    hikari:
      max-lifetime: 300000
      validation-timeout: 5000
      keepalive-time: 30000

---
spring:
  config:
    activate:
      on-profile: local

logging:
  level:
    root: INFO
    org.springframework.jdbc.core: WARN
    org.springframework.jdbc.datasource: WARN
    org.postgresql: WARN
    com.zaxxer.hikari: INFO

