-- =========================
-- invoice (테스트용 단순화)
-- =========================
CREATE TABLE invoice (
                         inv_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                         inv_no BIGINT NOT NULL,
                         sub_id BIGINT NOT NULL,
                         name VARCHAR(50) NOT NULL,
                         phone_enc VARCHAR(255) NOT NULL,
                         email_enc VARCHAR(255) NOT NULL,
                         created_at TIMESTAMP NOT NULL,
                         inv_month CHAR(6) NOT NULL,
                         total_amount INTEGER NOT NULL,
                         total_discount INTEGER NOT NULL,
                         total_price INTEGER NOT NULL,
                         due_date TIMESTAMP NOT NULL,
                         start_date TIMESTAMP NOT NULL,
                         end_date TIMESTAMP NOT NULL,
                         send_day INTEGER DEFAULT 20 NOT NULL,

                         CONSTRAINT pk_invoice PRIMARY KEY (inv_id, inv_month),
                         CONSTRAINT uk_invoice_sub_month UNIQUE (sub_id, inv_month)
);

CREATE INDEX idx_invoice_sub_id ON invoice (sub_id);

-- =========================
-- invoice_item (테스트용)
-- =========================
CREATE TABLE invoice_item (
                              item_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                              sub_id BIGINT NOT NULL,
                              inv_month CHAR(6) NOT NULL,
                              name VARCHAR(30) NOT NULL,
                              type VARCHAR(10) NOT NULL,
                              value_type VARCHAR(10) NOT NULL,
                              "value" INTEGER NOT NULL,
                              created_at TIMESTAMP NOT NULL,

                              CONSTRAINT pk_invoice_item PRIMARY KEY (item_id, inv_month)
);

CREATE INDEX idx_invoice_item_sub_id ON invoice_item (sub_id);
